/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Wed Mar  8 21:59:49 2017. */

#include "lighthouse.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DarkRoomProtobuf_configObject_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, DarkRoomProtobuf_configObject, ip, ip, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DarkRoomProtobuf_configObject, logging_port, ip, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, DarkRoomProtobuf_configObject, sensor_port, logging_port, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, DarkRoomProtobuf_configObject, imu_port, sensor_port, 0),
    PB_LAST_FIELD
};

const pb_field_t DarkRoomProtobuf_trackedObjectConfig_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, DarkRoomProtobuf_trackedObjectConfig, ip, ip, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DarkRoomProtobuf_trackedObjectConfig, command_port, ip, 0),
    PB_LAST_FIELD
};

const pb_field_t DarkRoomProtobuf_loggingObject_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, DarkRoomProtobuf_loggingObject, message, message, 0),
    PB_LAST_FIELD
};

const pb_field_t DarkRoomProtobuf_commandObject_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DarkRoomProtobuf_commandObject, command, command, 0),
    PB_LAST_FIELD
};

const pb_field_t DarkRoomProtobuf_imuObject_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DarkRoomProtobuf_imuObject, id, id, 0),
    PB_FIELD(  2, FLOAT   , REPEATED, STATIC  , OTHER, DarkRoomProtobuf_imuObject, quaternion, id, 0),
    PB_FIELD(  3, INT32   , REPEATED, STATIC  , OTHER, DarkRoomProtobuf_imuObject, acc, quaternion, 0),
    PB_FIELD(  4, FLOAT   , REPEATED, STATIC  , OTHER, DarkRoomProtobuf_imuObject, gravity, acc, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
